In [2]:
import numpy as np

## Creating array

In [3]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [4]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [6]:
a1 = np.array([1,23,4])

In [7]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1,2,3],
              [4,5,6]])

In [10]:
type(a2)

numpy.ndarray

In [11]:
a2.shape

(2, 3)

In [12]:
a2.ndim

2

In [13]:
a2.dtype

dtype('int64')

In [14]:
a2.size

6

## Creating Numpy Arrays from Scratch

### zeros, ones, full, arange, linspace

In [17]:
np.zeros([2,4], dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
np.ones([3,5], dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
np.full([3,5], 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [22]:
np.linspace(0,1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random

In [23]:
np.random.random((4,4))

array([[0.46596008, 0.74448466, 0.02294844, 0.94704998],
       [0.66754205, 0.69890788, 0.57986813, 0.08387975],
       [0.15778187, 0.02031717, 0.93134246, 0.91194436],
       [0.14592656, 0.98969633, 0.06414282, 0.86927781]])

In [26]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [27]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [28]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])